# coding: utf-8

"""
    

    

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import lib_openshift
from lib_openshift.rest import ApiException
from lib_openshift.apis.oapiv_api import OapivApi


class TestOapivApi(unittest.TestCase):
    """ OapivApi unit test stubs """

    def setUp(self):
        self.api = lib_openshift.apis.oapiv_api.OapivApi()

    def tearDown(self):
        pass

    def test_connect_post_namespaced_binary_build_request_options_instantiatebinary(self):
        """
        Test case for connect_post_namespaced_binary_build_request_options_instantiatebinary

        connect POST requests to instantiatebinary of BinaryBuildRequestOptions
        """
        pass

    def test_connect_post_namespaced_status_webhooks(self):
        """
        Test case for connect_post_namespaced_status_webhooks

        connect POST requests to webhooks of Status
        """
        pass

    def test_connect_post_namespaced_status_webhooks_0(self):
        """
        Test case for connect_post_namespaced_status_webhooks_0

        connect POST requests to webhooks of Status
        """
        pass

    def test_create_build(self):
        """
        Test case for create_build

        create a Build
        """
        pass

    def test_create_build_config(self):
        """
        Test case for create_build_config

        create a BuildConfig
        """
        pass

    def test_create_deployment_config(self):
        """
        Test case for create_deployment_config

        create a DeploymentConfig
        """
        pass

    def test_create_deployment_config_rollback(self):
        """
        Test case for create_deployment_config_rollback

        create a DeploymentConfigRollback
        """
        pass

    def test_create_image_stream(self):
        """
        Test case for create_image_stream

        create a ImageStream
        """
        pass

    def test_create_image_stream_import(self):
        """
        Test case for create_image_stream_import

        create a ImageStreamImport
        """
        pass

    def test_create_image_stream_mapping(self):
        """
        Test case for create_image_stream_mapping

        create a ImageStreamMapping
        """
        pass

    def test_create_local_resource_access_review(self):
        """
        Test case for create_local_resource_access_review

        create a LocalResourceAccessReview
        """
        pass

    def test_create_local_subject_access_review(self):
        """
        Test case for create_local_subject_access_review

        create a LocalSubjectAccessReview
        """
        pass

    def test_create_namespaced_build(self):
        """
        Test case for create_namespaced_build

        create a Build
        """
        pass

    def test_create_namespaced_build_config(self):
        """
        Test case for create_namespaced_build_config

        create a BuildConfig
        """
        pass

    def test_create_namespaced_build_request_clone(self):
        """
        Test case for create_namespaced_build_request_clone

        create clone of a BuildRequest
        """
        pass

    def test_create_namespaced_build_request_instantiate(self):
        """
        Test case for create_namespaced_build_request_instantiate

        create instantiate of a BuildRequest
        """
        pass

    def test_create_namespaced_cluster_network(self):
        """
        Test case for create_namespaced_cluster_network

        create a ClusterNetwork
        """
        pass

    def test_create_namespaced_cluster_policy(self):
        """
        Test case for create_namespaced_cluster_policy

        create a ClusterPolicy
        """
        pass

    def test_create_namespaced_cluster_policy_binding(self):
        """
        Test case for create_namespaced_cluster_policy_binding

        create a ClusterPolicyBinding
        """
        pass

    def test_create_namespaced_cluster_role(self):
        """
        Test case for create_namespaced_cluster_role

        create a ClusterRole
        """
        pass

    def test_create_namespaced_cluster_role_binding(self):
        """
        Test case for create_namespaced_cluster_role_binding

        create a ClusterRoleBinding
        """
        pass

    def test_create_namespaced_deployment_config(self):
        """
        Test case for create_namespaced_deployment_config

        create a DeploymentConfig
        """
        pass

    def test_create_namespaced_deployment_config_rollback(self):
        """
        Test case for create_namespaced_deployment_config_rollback

        create a DeploymentConfigRollback
        """
        pass

    def test_create_namespaced_group(self):
        """
        Test case for create_namespaced_group

        create a Group
        """
        pass

    def test_create_namespaced_host_subnet(self):
        """
        Test case for create_namespaced_host_subnet

        create a HostSubnet
        """
        pass

    def test_create_namespaced_identity(self):
        """
        Test case for create_namespaced_identity

        create a Identity
        """
        pass

    def test_create_namespaced_image(self):
        """
        Test case for create_namespaced_image

        create a Image
        """
        pass

    def test_create_namespaced_image_stream(self):
        """
        Test case for create_namespaced_image_stream

        create a ImageStream
        """
        pass

    def test_create_namespaced_image_stream_import(self):
        """
        Test case for create_namespaced_image_stream_import

        create a ImageStreamImport
        """
        pass

    def test_create_namespaced_image_stream_mapping(self):
        """
        Test case for create_namespaced_image_stream_mapping

        create a ImageStreamMapping
        """
        pass

    def test_create_namespaced_local_resource_access_review(self):
        """
        Test case for create_namespaced_local_resource_access_review

        create a LocalResourceAccessReview
        """
        pass

    def test_create_namespaced_local_subject_access_review(self):
        """
        Test case for create_namespaced_local_subject_access_review

        create a LocalSubjectAccessReview
        """
        pass

    def test_create_namespaced_net_namespace(self):
        """
        Test case for create_namespaced_net_namespace

        create a NetNamespace
        """
        pass

    def test_create_namespaced_o_auth_access_token(self):
        """
        Test case for create_namespaced_o_auth_access_token

        create a OAuthAccessToken
        """
        pass

    def test_create_namespaced_o_auth_authorize_token(self):
        """
        Test case for create_namespaced_o_auth_authorize_token

        create a OAuthAuthorizeToken
        """
        pass

    def test_create_namespaced_o_auth_client(self):
        """
        Test case for create_namespaced_o_auth_client

        create a OAuthClient
        """
        pass

    def test_create_namespaced_o_auth_client_authorization(self):
        """
        Test case for create_namespaced_o_auth_client_authorization

        create a OAuthClientAuthorization
        """
        pass

    def test_create_namespaced_policy(self):
        """
        Test case for create_namespaced_policy

        create a Policy
        """
        pass

    def test_create_namespaced_policy_binding(self):
        """
        Test case for create_namespaced_policy_binding

        create a PolicyBinding
        """
        pass

    def test_create_namespaced_project(self):
        """
        Test case for create_namespaced_project

        create a Project
        """
        pass

    def test_create_namespaced_project_request(self):
        """
        Test case for create_namespaced_project_request

        create a ProjectRequest
        """
        pass

    def test_create_namespaced_resource_access_review(self):
        """
        Test case for create_namespaced_resource_access_review

        create a ResourceAccessReview
        """
        pass

    def test_create_namespaced_role(self):
        """
        Test case for create_namespaced_role

        create a Role
        """
        pass

    def test_create_namespaced_role_binding(self):
        """
        Test case for create_namespaced_role_binding

        create a RoleBinding
        """
        pass

    def test_create_namespaced_route(self):
        """
        Test case for create_namespaced_route

        create a Route
        """
        pass

    def test_create_namespaced_subject_access_review(self):
        """
        Test case for create_namespaced_subject_access_review

        create a SubjectAccessReview
        """
        pass

    def test_create_namespaced_template(self):
        """
        Test case for create_namespaced_template

        create a Template
        """
        pass

    def test_create_namespaced_template_0(self):
        """
        Test case for create_namespaced_template_0

        create a Template
        """
        pass

    def test_create_namespaced_user(self):
        """
        Test case for create_namespaced_user

        create a User
        """
        pass

    def test_create_namespaced_user_identity_mapping(self):
        """
        Test case for create_namespaced_user_identity_mapping

        create a UserIdentityMapping
        """
        pass

    def test_create_policy(self):
        """
        Test case for create_policy

        create a Policy
        """
        pass

    def test_create_policy_binding(self):
        """
        Test case for create_policy_binding

        create a PolicyBinding
        """
        pass

    def test_create_resource_access_review(self):
        """
        Test case for create_resource_access_review

        create a ResourceAccessReview
        """
        pass

    def test_create_role(self):
        """
        Test case for create_role

        create a Role
        """
        pass

    def test_create_role_binding(self):
        """
        Test case for create_role_binding

        create a RoleBinding
        """
        pass

    def test_create_route(self):
        """
        Test case for create_route

        create a Route
        """
        pass

    def test_create_subject_access_review(self):
        """
        Test case for create_subject_access_review

        create a SubjectAccessReview
        """
        pass

    def test_create_template(self):
        """
        Test case for create_template

        create a Template
        """
        pass

    def test_create_template_0(self):
        """
        Test case for create_template_0

        create a Template
        """
        pass

    def test_delete_namespaced_build(self):
        """
        Test case for delete_namespaced_build

        delete a Build
        """
        pass

    def test_delete_namespaced_build_config(self):
        """
        Test case for delete_namespaced_build_config

        delete a BuildConfig
        """
        pass

    def test_delete_namespaced_cluster_network(self):
        """
        Test case for delete_namespaced_cluster_network

        delete a ClusterNetwork
        """
        pass

    def test_delete_namespaced_cluster_policy(self):
        """
        Test case for delete_namespaced_cluster_policy

        delete a ClusterPolicy
        """
        pass

    def test_delete_namespaced_cluster_policy_binding(self):
        """
        Test case for delete_namespaced_cluster_policy_binding

        delete a ClusterPolicyBinding
        """
        pass

    def test_delete_namespaced_cluster_role(self):
        """
        Test case for delete_namespaced_cluster_role

        delete a ClusterRole
        """
        pass

    def test_delete_namespaced_cluster_role_binding(self):
        """
        Test case for delete_namespaced_cluster_role_binding

        delete a ClusterRoleBinding
        """
        pass

    def test_delete_namespaced_deployment_config(self):
        """
        Test case for delete_namespaced_deployment_config

        delete a DeploymentConfig
        """
        pass

    def test_delete_namespaced_group(self):
        """
        Test case for delete_namespaced_group

        delete a Group
        """
        pass

    def test_delete_namespaced_host_subnet(self):
        """
        Test case for delete_namespaced_host_subnet

        delete a HostSubnet
        """
        pass

    def test_delete_namespaced_identity(self):
        """
        Test case for delete_namespaced_identity

        delete a Identity
        """
        pass

    def test_delete_namespaced_image(self):
        """
        Test case for delete_namespaced_image

        delete a Image
        """
        pass

    def test_delete_namespaced_image_stream(self):
        """
        Test case for delete_namespaced_image_stream

        delete a ImageStream
        """
        pass

    def test_delete_namespaced_image_stream_tag(self):
        """
        Test case for delete_namespaced_image_stream_tag

        delete a ImageStreamTag
        """
        pass

    def test_delete_namespaced_net_namespace(self):
        """
        Test case for delete_namespaced_net_namespace

        delete a NetNamespace
        """
        pass

    def test_delete_namespaced_o_auth_access_token(self):
        """
        Test case for delete_namespaced_o_auth_access_token

        delete a OAuthAccessToken
        """
        pass

    def test_delete_namespaced_o_auth_authorize_token(self):
        """
        Test case for delete_namespaced_o_auth_authorize_token

        delete a OAuthAuthorizeToken
        """
        pass

    def test_delete_namespaced_o_auth_client(self):
        """
        Test case for delete_namespaced_o_auth_client

        delete a OAuthClient
        """
        pass

    def test_delete_namespaced_o_auth_client_authorization(self):
        """
        Test case for delete_namespaced_o_auth_client_authorization

        delete a OAuthClientAuthorization
        """
        pass

    def test_delete_namespaced_policy(self):
        """
        Test case for delete_namespaced_policy

        delete a Policy
        """
        pass

    def test_delete_namespaced_policy_binding(self):
        """
        Test case for delete_namespaced_policy_binding

        delete a PolicyBinding
        """
        pass

    def test_delete_namespaced_project(self):
        """
        Test case for delete_namespaced_project

        delete a Project
        """
        pass

    def test_delete_namespaced_role(self):
        """
        Test case for delete_namespaced_role

        delete a Role
        """
        pass

    def test_delete_namespaced_role_binding(self):
        """
        Test case for delete_namespaced_role_binding

        delete a RoleBinding
        """
        pass

    def test_delete_namespaced_route(self):
        """
        Test case for delete_namespaced_route

        delete a Route
        """
        pass

    def test_delete_namespaced_template(self):
        """
        Test case for delete_namespaced_template

        delete a Template
        """
        pass

    def test_delete_namespaced_user(self):
        """
        Test case for delete_namespaced_user

        delete a User
        """
        pass

    def test_delete_namespaced_user_identity_mapping(self):
        """
        Test case for delete_namespaced_user_identity_mapping

        delete a UserIdentityMapping
        """
        pass

    def test_deletecollection_namespaced_build(self):
        """
        Test case for deletecollection_namespaced_build

        delete collection of Build
        """
        pass

    def test_deletecollection_namespaced_build_config(self):
        """
        Test case for deletecollection_namespaced_build_config

        delete collection of BuildConfig
        """
        pass

    def test_deletecollection_namespaced_cluster_network(self):
        """
        Test case for deletecollection_namespaced_cluster_network

        delete collection of ClusterNetwork
        """
        pass

    def test_deletecollection_namespaced_cluster_policy(self):
        """
        Test case for deletecollection_namespaced_cluster_policy

        delete collection of ClusterPolicy
        """
        pass

    def test_deletecollection_namespaced_cluster_policy_binding(self):
        """
        Test case for deletecollection_namespaced_cluster_policy_binding

        delete collection of ClusterPolicyBinding
        """
        pass

    def test_deletecollection_namespaced_deployment_config(self):
        """
        Test case for deletecollection_namespaced_deployment_config

        delete collection of DeploymentConfig
        """
        pass

    def test_deletecollection_namespaced_group(self):
        """
        Test case for deletecollection_namespaced_group

        delete collection of Group
        """
        pass

    def test_deletecollection_namespaced_host_subnet(self):
        """
        Test case for deletecollection_namespaced_host_subnet

        delete collection of HostSubnet
        """
        pass

    def test_deletecollection_namespaced_identity(self):
        """
        Test case for deletecollection_namespaced_identity

        delete collection of Identity
        """
        pass

    def test_deletecollection_namespaced_image(self):
        """
        Test case for deletecollection_namespaced_image

        delete collection of Image
        """
        pass

    def test_deletecollection_namespaced_image_stream(self):
        """
        Test case for deletecollection_namespaced_image_stream

        delete collection of ImageStream
        """
        pass

    def test_deletecollection_namespaced_net_namespace(self):
        """
        Test case for deletecollection_namespaced_net_namespace

        delete collection of NetNamespace
        """
        pass

    def test_deletecollection_namespaced_o_auth_client(self):
        """
        Test case for deletecollection_namespaced_o_auth_client

        delete collection of OAuthClient
        """
        pass

    def test_deletecollection_namespaced_o_auth_client_authorization(self):
        """
        Test case for deletecollection_namespaced_o_auth_client_authorization

        delete collection of OAuthClientAuthorization
        """
        pass

    def test_deletecollection_namespaced_policy(self):
        """
        Test case for deletecollection_namespaced_policy

        delete collection of Policy
        """
        pass

    def test_deletecollection_namespaced_policy_binding(self):
        """
        Test case for deletecollection_namespaced_policy_binding

        delete collection of PolicyBinding
        """
        pass

    def test_deletecollection_namespaced_route(self):
        """
        Test case for deletecollection_namespaced_route

        delete collection of Route
        """
        pass

    def test_deletecollection_namespaced_template(self):
        """
        Test case for deletecollection_namespaced_template

        delete collection of Template
        """
        pass

    def test_deletecollection_namespaced_user(self):
        """
        Test case for deletecollection_namespaced_user

        delete collection of User
        """
        pass

    def test_get_api_resources(self):
        """
        Test case for get_api_resources

        get available resources
        """
        pass

    def test_list_build(self):
        """
        Test case for list_build

        list or watch objects of kind Build
        """
        pass

    def test_list_build_config(self):
        """
        Test case for list_build_config

        list or watch objects of kind BuildConfig
        """
        pass

    def test_list_deployment_config(self):
        """
        Test case for list_deployment_config

        list or watch objects of kind DeploymentConfig
        """
        pass

    def test_list_image_stream(self):
        """
        Test case for list_image_stream

        list or watch objects of kind ImageStream
        """
        pass

    def test_list_image_stream_tag(self):
        """
        Test case for list_image_stream_tag

        list objects of kind ImageStreamTag
        """
        pass

    def test_list_namespaced_build(self):
        """
        Test case for list_namespaced_build

        list or watch objects of kind Build
        """
        pass

    def test_list_namespaced_build_config(self):
        """
        Test case for list_namespaced_build_config

        list or watch objects of kind BuildConfig
        """
        pass

    def test_list_namespaced_cluster_network(self):
        """
        Test case for list_namespaced_cluster_network

        list or watch objects of kind ClusterNetwork
        """
        pass

    def test_list_namespaced_cluster_policy(self):
        """
        Test case for list_namespaced_cluster_policy

        list or watch objects of kind ClusterPolicy
        """
        pass

    def test_list_namespaced_cluster_policy_binding(self):
        """
        Test case for list_namespaced_cluster_policy_binding

        list or watch objects of kind ClusterPolicyBinding
        """
        pass

    def test_list_namespaced_cluster_role(self):
        """
        Test case for list_namespaced_cluster_role

        list objects of kind ClusterRole
        """
        pass

    def test_list_namespaced_cluster_role_binding(self):
        """
        Test case for list_namespaced_cluster_role_binding

        list objects of kind ClusterRoleBinding
        """
        pass

    def test_list_namespaced_deployment_config(self):
        """
        Test case for list_namespaced_deployment_config

        list or watch objects of kind DeploymentConfig
        """
        pass

    def test_list_namespaced_group(self):
        """
        Test case for list_namespaced_group

        list or watch objects of kind Group
        """
        pass

    def test_list_namespaced_host_subnet(self):
        """
        Test case for list_namespaced_host_subnet

        list or watch objects of kind HostSubnet
        """
        pass

    def test_list_namespaced_identity(self):
        """
        Test case for list_namespaced_identity

        list or watch objects of kind Identity
        """
        pass

    def test_list_namespaced_image(self):
        """
        Test case for list_namespaced_image

        list or watch objects of kind Image
        """
        pass

    def test_list_namespaced_image_stream(self):
        """
        Test case for list_namespaced_image_stream

        list or watch objects of kind ImageStream
        """
        pass

    def test_list_namespaced_image_stream_tag(self):
        """
        Test case for list_namespaced_image_stream_tag

        list objects of kind ImageStreamTag
        """
        pass

    def test_list_namespaced_net_namespace(self):
        """
        Test case for list_namespaced_net_namespace

        list or watch objects of kind NetNamespace
        """
        pass

    def test_list_namespaced_o_auth_access_token(self):
        """
        Test case for list_namespaced_o_auth_access_token

        list objects of kind OAuthAccessToken
        """
        pass

    def test_list_namespaced_o_auth_authorize_token(self):
        """
        Test case for list_namespaced_o_auth_authorize_token

        list objects of kind OAuthAuthorizeToken
        """
        pass

    def test_list_namespaced_o_auth_client(self):
        """
        Test case for list_namespaced_o_auth_client

        list or watch objects of kind OAuthClient
        """
        pass

    def test_list_namespaced_o_auth_client_authorization(self):
        """
        Test case for list_namespaced_o_auth_client_authorization

        list or watch objects of kind OAuthClientAuthorization
        """
        pass

    def test_list_namespaced_policy(self):
        """
        Test case for list_namespaced_policy

        list or watch objects of kind Policy
        """
        pass

    def test_list_namespaced_policy_binding(self):
        """
        Test case for list_namespaced_policy_binding

        list or watch objects of kind PolicyBinding
        """
        pass

    def test_list_namespaced_project(self):
        """
        Test case for list_namespaced_project

        list objects of kind Project
        """
        pass

    def test_list_namespaced_project_request(self):
        """
        Test case for list_namespaced_project_request

        list objects of kind ProjectRequest
        """
        pass

    def test_list_namespaced_role(self):
        """
        Test case for list_namespaced_role

        list objects of kind Role
        """
        pass

    def test_list_namespaced_role_binding(self):
        """
        Test case for list_namespaced_role_binding

        list objects of kind RoleBinding
        """
        pass

    def test_list_namespaced_route(self):
        """
        Test case for list_namespaced_route

        list or watch objects of kind Route
        """
        pass

    def test_list_namespaced_template(self):
        """
        Test case for list_namespaced_template

        list or watch objects of kind Template
        """
        pass

    def test_list_namespaced_user(self):
        """
        Test case for list_namespaced_user

        list or watch objects of kind User
        """
        pass

    def test_list_policy(self):
        """
        Test case for list_policy

        list or watch objects of kind Policy
        """
        pass

    def test_list_policy_binding(self):
        """
        Test case for list_policy_binding

        list or watch objects of kind PolicyBinding
        """
        pass

    def test_list_role(self):
        """
        Test case for list_role

        list objects of kind Role
        """
        pass

    def test_list_role_binding(self):
        """
        Test case for list_role_binding

        list objects of kind RoleBinding
        """
        pass

    def test_list_route(self):
        """
        Test case for list_route

        list or watch objects of kind Route
        """
        pass

    def test_list_template(self):
        """
        Test case for list_template

        list or watch objects of kind Template
        """
        pass

    def test_patch_namespaced_build(self):
        """
        Test case for patch_namespaced_build

        partially update the specified Build
        """
        pass

    def test_patch_namespaced_build_config(self):
        """
        Test case for patch_namespaced_build_config

        partially update the specified BuildConfig
        """
        pass

    def test_patch_namespaced_cluster_network(self):
        """
        Test case for patch_namespaced_cluster_network

        partially update the specified ClusterNetwork
        """
        pass

    def test_patch_namespaced_cluster_policy(self):
        """
        Test case for patch_namespaced_cluster_policy

        partially update the specified ClusterPolicy
        """
        pass

    def test_patch_namespaced_cluster_policy_binding(self):
        """
        Test case for patch_namespaced_cluster_policy_binding

        partially update the specified ClusterPolicyBinding
        """
        pass

    def test_patch_namespaced_cluster_role(self):
        """
        Test case for patch_namespaced_cluster_role

        partially update the specified ClusterRole
        """
        pass

    def test_patch_namespaced_cluster_role_binding(self):
        """
        Test case for patch_namespaced_cluster_role_binding

        partially update the specified ClusterRoleBinding
        """
        pass

    def test_patch_namespaced_deployment_config(self):
        """
        Test case for patch_namespaced_deployment_config

        partially update the specified DeploymentConfig
        """
        pass

    def test_patch_namespaced_group(self):
        """
        Test case for patch_namespaced_group

        partially update the specified Group
        """
        pass

    def test_patch_namespaced_host_subnet(self):
        """
        Test case for patch_namespaced_host_subnet

        partially update the specified HostSubnet
        """
        pass

    def test_patch_namespaced_identity(self):
        """
        Test case for patch_namespaced_identity

        partially update the specified Identity
        """
        pass

    def test_patch_namespaced_image(self):
        """
        Test case for patch_namespaced_image

        partially update the specified Image
        """
        pass

    def test_patch_namespaced_image_stream(self):
        """
        Test case for patch_namespaced_image_stream

        partially update the specified ImageStream
        """
        pass

    def test_patch_namespaced_image_stream_tag(self):
        """
        Test case for patch_namespaced_image_stream_tag

        partially update the specified ImageStreamTag
        """
        pass

    def test_patch_namespaced_net_namespace(self):
        """
        Test case for patch_namespaced_net_namespace

        partially update the specified NetNamespace
        """
        pass

    def test_patch_namespaced_o_auth_client(self):
        """
        Test case for patch_namespaced_o_auth_client

        partially update the specified OAuthClient
        """
        pass

    def test_patch_namespaced_o_auth_client_authorization(self):
        """
        Test case for patch_namespaced_o_auth_client_authorization

        partially update the specified OAuthClientAuthorization
        """
        pass

    def test_patch_namespaced_policy(self):
        """
        Test case for patch_namespaced_policy

        partially update the specified Policy
        """
        pass

    def test_patch_namespaced_policy_binding(self):
        """
        Test case for patch_namespaced_policy_binding

        partially update the specified PolicyBinding
        """
        pass

    def test_patch_namespaced_project(self):
        """
        Test case for patch_namespaced_project

        partially update the specified Project
        """
        pass

    def test_patch_namespaced_role(self):
        """
        Test case for patch_namespaced_role

        partially update the specified Role
        """
        pass

    def test_patch_namespaced_role_binding(self):
        """
        Test case for patch_namespaced_role_binding

        partially update the specified RoleBinding
        """
        pass

    def test_patch_namespaced_route(self):
        """
        Test case for patch_namespaced_route

        partially update the specified Route
        """
        pass

    def test_patch_namespaced_scale_scale(self):
        """
        Test case for patch_namespaced_scale_scale

        partially update scale of the specified Scale
        """
        pass

    def test_patch_namespaced_template(self):
        """
        Test case for patch_namespaced_template

        partially update the specified Template
        """
        pass

    def test_patch_namespaced_user(self):
        """
        Test case for patch_namespaced_user

        partially update the specified User
        """
        pass

    def test_patch_namespaced_user_identity_mapping(self):
        """
        Test case for patch_namespaced_user_identity_mapping

        partially update the specified UserIdentityMapping
        """
        pass

    def test_read_namespaced_build(self):
        """
        Test case for read_namespaced_build

        read the specified Build
        """
        pass

    def test_read_namespaced_build_config(self):
        """
        Test case for read_namespaced_build_config

        read the specified BuildConfig
        """
        pass

    def test_read_namespaced_build_log_log(self):
        """
        Test case for read_namespaced_build_log_log

        read log of the specified BuildLog
        """
        pass

    def test_read_namespaced_cluster_network(self):
        """
        Test case for read_namespaced_cluster_network

        read the specified ClusterNetwork
        """
        pass

    def test_read_namespaced_cluster_policy(self):
        """
        Test case for read_namespaced_cluster_policy

        read the specified ClusterPolicy
        """
        pass

    def test_read_namespaced_cluster_policy_binding(self):
        """
        Test case for read_namespaced_cluster_policy_binding

        read the specified ClusterPolicyBinding
        """
        pass

    def test_read_namespaced_cluster_role(self):
        """
        Test case for read_namespaced_cluster_role

        read the specified ClusterRole
        """
        pass

    def test_read_namespaced_cluster_role_binding(self):
        """
        Test case for read_namespaced_cluster_role_binding

        read the specified ClusterRoleBinding
        """
        pass

    def test_read_namespaced_deployment_config(self):
        """
        Test case for read_namespaced_deployment_config

        read the specified DeploymentConfig
        """
        pass

    def test_read_namespaced_deployment_config_0(self):
        """
        Test case for read_namespaced_deployment_config_0

        read the specified DeploymentConfig
        """
        pass

    def test_read_namespaced_deployment_log_log(self):
        """
        Test case for read_namespaced_deployment_log_log

        read log of the specified DeploymentLog
        """
        pass

    def test_read_namespaced_group(self):
        """
        Test case for read_namespaced_group

        read the specified Group
        """
        pass

    def test_read_namespaced_host_subnet(self):
        """
        Test case for read_namespaced_host_subnet

        read the specified HostSubnet
        """
        pass

    def test_read_namespaced_identity(self):
        """
        Test case for read_namespaced_identity

        read the specified Identity
        """
        pass

    def test_read_namespaced_image(self):
        """
        Test case for read_namespaced_image

        read the specified Image
        """
        pass

    def test_read_namespaced_image_stream(self):
        """
        Test case for read_namespaced_image_stream

        read the specified ImageStream
        """
        pass

    def test_read_namespaced_image_stream_image(self):
        """
        Test case for read_namespaced_image_stream_image

        read the specified ImageStreamImage
        """
        pass

    def test_read_namespaced_image_stream_tag(self):
        """
        Test case for read_namespaced_image_stream_tag

        read the specified ImageStreamTag
        """
        pass

    def test_read_namespaced_net_namespace(self):
        """
        Test case for read_namespaced_net_namespace

        read the specified NetNamespace
        """
        pass

    def test_read_namespaced_o_auth_access_token(self):
        """
        Test case for read_namespaced_o_auth_access_token

        read the specified OAuthAccessToken
        """
        pass

    def test_read_namespaced_o_auth_authorize_token(self):
        """
        Test case for read_namespaced_o_auth_authorize_token

        read the specified OAuthAuthorizeToken
        """
        pass

    def test_read_namespaced_o_auth_client(self):
        """
        Test case for read_namespaced_o_auth_client

        read the specified OAuthClient
        """
        pass

    def test_read_namespaced_o_auth_client_authorization(self):
        """
        Test case for read_namespaced_o_auth_client_authorization

        read the specified OAuthClientAuthorization
        """
        pass

    def test_read_namespaced_policy(self):
        """
        Test case for read_namespaced_policy

        read the specified Policy
        """
        pass

    def test_read_namespaced_policy_binding(self):
        """
        Test case for read_namespaced_policy_binding

        read the specified PolicyBinding
        """
        pass

    def test_read_namespaced_project(self):
        """
        Test case for read_namespaced_project

        read the specified Project
        """
        pass

    def test_read_namespaced_role(self):
        """
        Test case for read_namespaced_role

        read the specified Role
        """
        pass

    def test_read_namespaced_role_binding(self):
        """
        Test case for read_namespaced_role_binding

        read the specified RoleBinding
        """
        pass

    def test_read_namespaced_route(self):
        """
        Test case for read_namespaced_route

        read the specified Route
        """
        pass

    def test_read_namespaced_scale_scale(self):
        """
        Test case for read_namespaced_scale_scale

        read scale of the specified Scale
        """
        pass

    def test_read_namespaced_secret_list_secrets(self):
        """
        Test case for read_namespaced_secret_list_secrets

        read secrets of the specified SecretList
        """
        pass

    def test_read_namespaced_template(self):
        """
        Test case for read_namespaced_template

        read the specified Template
        """
        pass

    def test_read_namespaced_user(self):
        """
        Test case for read_namespaced_user

        read the specified User
        """
        pass

    def test_read_namespaced_user_identity_mapping(self):
        """
        Test case for read_namespaced_user_identity_mapping

        read the specified UserIdentityMapping
        """
        pass

    def test_replace_namespaced_build(self):
        """
        Test case for replace_namespaced_build

        replace the specified Build
        """
        pass

    def test_replace_namespaced_build_config(self):
        """
        Test case for replace_namespaced_build_config

        replace the specified BuildConfig
        """
        pass

    def test_replace_namespaced_build_details(self):
        """
        Test case for replace_namespaced_build_details

        replace details of the specified Build
        """
        pass

    def test_replace_namespaced_cluster_network(self):
        """
        Test case for replace_namespaced_cluster_network

        replace the specified ClusterNetwork
        """
        pass

    def test_replace_namespaced_cluster_policy(self):
        """
        Test case for replace_namespaced_cluster_policy

        replace the specified ClusterPolicy
        """
        pass

    def test_replace_namespaced_cluster_policy_binding(self):
        """
        Test case for replace_namespaced_cluster_policy_binding

        replace the specified ClusterPolicyBinding
        """
        pass

    def test_replace_namespaced_cluster_role(self):
        """
        Test case for replace_namespaced_cluster_role

        replace the specified ClusterRole
        """
        pass

    def test_replace_namespaced_cluster_role_binding(self):
        """
        Test case for replace_namespaced_cluster_role_binding

        replace the specified ClusterRoleBinding
        """
        pass

    def test_replace_namespaced_deployment_config(self):
        """
        Test case for replace_namespaced_deployment_config

        replace the specified DeploymentConfig
        """
        pass

    def test_replace_namespaced_group(self):
        """
        Test case for replace_namespaced_group

        replace the specified Group
        """
        pass

    def test_replace_namespaced_host_subnet(self):
        """
        Test case for replace_namespaced_host_subnet

        replace the specified HostSubnet
        """
        pass

    def test_replace_namespaced_identity(self):
        """
        Test case for replace_namespaced_identity

        replace the specified Identity
        """
        pass

    def test_replace_namespaced_image(self):
        """
        Test case for replace_namespaced_image

        replace the specified Image
        """
        pass

    def test_replace_namespaced_image_stream(self):
        """
        Test case for replace_namespaced_image_stream

        replace the specified ImageStream
        """
        pass

    def test_replace_namespaced_image_stream_status(self):
        """
        Test case for replace_namespaced_image_stream_status

        replace status of the specified ImageStream
        """
        pass

    def test_replace_namespaced_image_stream_tag(self):
        """
        Test case for replace_namespaced_image_stream_tag

        replace the specified ImageStreamTag
        """
        pass

    def test_replace_namespaced_net_namespace(self):
        """
        Test case for replace_namespaced_net_namespace

        replace the specified NetNamespace
        """
        pass

    def test_replace_namespaced_o_auth_client(self):
        """
        Test case for replace_namespaced_o_auth_client

        replace the specified OAuthClient
        """
        pass

    def test_replace_namespaced_o_auth_client_authorization(self):
        """
        Test case for replace_namespaced_o_auth_client_authorization

        replace the specified OAuthClientAuthorization
        """
        pass

    def test_replace_namespaced_policy(self):
        """
        Test case for replace_namespaced_policy

        replace the specified Policy
        """
        pass

    def test_replace_namespaced_policy_binding(self):
        """
        Test case for replace_namespaced_policy_binding

        replace the specified PolicyBinding
        """
        pass

    def test_replace_namespaced_project(self):
        """
        Test case for replace_namespaced_project

        replace the specified Project
        """
        pass

    def test_replace_namespaced_role(self):
        """
        Test case for replace_namespaced_role

        replace the specified Role
        """
        pass

    def test_replace_namespaced_role_binding(self):
        """
        Test case for replace_namespaced_role_binding

        replace the specified RoleBinding
        """
        pass

    def test_replace_namespaced_route(self):
        """
        Test case for replace_namespaced_route

        replace the specified Route
        """
        pass

    def test_replace_namespaced_route_status(self):
        """
        Test case for replace_namespaced_route_status

        replace status of the specified Route
        """
        pass

    def test_replace_namespaced_scale_scale(self):
        """
        Test case for replace_namespaced_scale_scale

        replace scale of the specified Scale
        """
        pass

    def test_replace_namespaced_template(self):
        """
        Test case for replace_namespaced_template

        replace the specified Template
        """
        pass

    def test_replace_namespaced_user(self):
        """
        Test case for replace_namespaced_user

        replace the specified User
        """
        pass

    def test_replace_namespaced_user_identity_mapping(self):
        """
        Test case for replace_namespaced_user_identity_mapping

        replace the specified UserIdentityMapping
        """
        pass

    def test_watch_build_config_list(self):
        """
        Test case for watch_build_config_list

        watch individual changes to a list of BuildConfig
        """
        pass

    def test_watch_build_list(self):
        """
        Test case for watch_build_list

        watch individual changes to a list of Build
        """
        pass

    def test_watch_deployment_config_list(self):
        """
        Test case for watch_deployment_config_list

        watch individual changes to a list of DeploymentConfig
        """
        pass

    def test_watch_image_stream_list(self):
        """
        Test case for watch_image_stream_list

        watch individual changes to a list of ImageStream
        """
        pass

    def test_watch_namespaced_build(self):
        """
        Test case for watch_namespaced_build

        watch changes to an object of kind Build
        """
        pass

    def test_watch_namespaced_build_config(self):
        """
        Test case for watch_namespaced_build_config

        watch changes to an object of kind BuildConfig
        """
        pass

    def test_watch_namespaced_build_config_list(self):
        """
        Test case for watch_namespaced_build_config_list

        watch individual changes to a list of BuildConfig
        """
        pass

    def test_watch_namespaced_build_list(self):
        """
        Test case for watch_namespaced_build_list

        watch individual changes to a list of Build
        """
        pass

    def test_watch_namespaced_cluster_network(self):
        """
        Test case for watch_namespaced_cluster_network

        watch changes to an object of kind ClusterNetwork
        """
        pass

    def test_watch_namespaced_cluster_network_list(self):
        """
        Test case for watch_namespaced_cluster_network_list

        watch individual changes to a list of ClusterNetwork
        """
        pass

    def test_watch_namespaced_cluster_policy(self):
        """
        Test case for watch_namespaced_cluster_policy

        watch changes to an object of kind ClusterPolicy
        """
        pass

    def test_watch_namespaced_cluster_policy_binding(self):
        """
        Test case for watch_namespaced_cluster_policy_binding

        watch changes to an object of kind ClusterPolicyBinding
        """
        pass

    def test_watch_namespaced_cluster_policy_binding_list(self):
        """
        Test case for watch_namespaced_cluster_policy_binding_list

        watch individual changes to a list of ClusterPolicyBinding
        """
        pass

    def test_watch_namespaced_cluster_policy_list(self):
        """
        Test case for watch_namespaced_cluster_policy_list

        watch individual changes to a list of ClusterPolicy
        """
        pass

    def test_watch_namespaced_deployment_config(self):
        """
        Test case for watch_namespaced_deployment_config

        watch changes to an object of kind DeploymentConfig
        """
        pass

    def test_watch_namespaced_deployment_config_list(self):
        """
        Test case for watch_namespaced_deployment_config_list

        watch individual changes to a list of DeploymentConfig
        """
        pass

    def test_watch_namespaced_group(self):
        """
        Test case for watch_namespaced_group

        watch changes to an object of kind Group
        """
        pass

    def test_watch_namespaced_group_list(self):
        """
        Test case for watch_namespaced_group_list

        watch individual changes to a list of Group
        """
        pass

    def test_watch_namespaced_host_subnet(self):
        """
        Test case for watch_namespaced_host_subnet

        watch changes to an object of kind HostSubnet
        """
        pass

    def test_watch_namespaced_host_subnet_list(self):
        """
        Test case for watch_namespaced_host_subnet_list

        watch individual changes to a list of HostSubnet
        """
        pass

    def test_watch_namespaced_identity(self):
        """
        Test case for watch_namespaced_identity

        watch changes to an object of kind Identity
        """
        pass

    def test_watch_namespaced_identity_list(self):
        """
        Test case for watch_namespaced_identity_list

        watch individual changes to a list of Identity
        """
        pass

    def test_watch_namespaced_image(self):
        """
        Test case for watch_namespaced_image

        watch changes to an object of kind Image
        """
        pass

    def test_watch_namespaced_image_list(self):
        """
        Test case for watch_namespaced_image_list

        watch individual changes to a list of Image
        """
        pass

    def test_watch_namespaced_image_stream(self):
        """
        Test case for watch_namespaced_image_stream

        watch changes to an object of kind ImageStream
        """
        pass

    def test_watch_namespaced_image_stream_list(self):
        """
        Test case for watch_namespaced_image_stream_list

        watch individual changes to a list of ImageStream
        """
        pass

    def test_watch_namespaced_net_namespace(self):
        """
        Test case for watch_namespaced_net_namespace

        watch changes to an object of kind NetNamespace
        """
        pass

    def test_watch_namespaced_net_namespace_list(self):
        """
        Test case for watch_namespaced_net_namespace_list

        watch individual changes to a list of NetNamespace
        """
        pass

    def test_watch_namespaced_o_auth_client(self):
        """
        Test case for watch_namespaced_o_auth_client

        watch changes to an object of kind OAuthClient
        """
        pass

    def test_watch_namespaced_o_auth_client_authorization(self):
        """
        Test case for watch_namespaced_o_auth_client_authorization

        watch changes to an object of kind OAuthClientAuthorization
        """
        pass

    def test_watch_namespaced_o_auth_client_authorization_list(self):
        """
        Test case for watch_namespaced_o_auth_client_authorization_list

        watch individual changes to a list of OAuthClientAuthorization
        """
        pass

    def test_watch_namespaced_o_auth_client_list(self):
        """
        Test case for watch_namespaced_o_auth_client_list

        watch individual changes to a list of OAuthClient
        """
        pass

    def test_watch_namespaced_policy(self):
        """
        Test case for watch_namespaced_policy

        watch changes to an object of kind Policy
        """
        pass

    def test_watch_namespaced_policy_binding(self):
        """
        Test case for watch_namespaced_policy_binding

        watch changes to an object of kind PolicyBinding
        """
        pass

    def test_watch_namespaced_policy_binding_list(self):
        """
        Test case for watch_namespaced_policy_binding_list

        watch individual changes to a list of PolicyBinding
        """
        pass

    def test_watch_namespaced_policy_list(self):
        """
        Test case for watch_namespaced_policy_list

        watch individual changes to a list of Policy
        """
        pass

    def test_watch_namespaced_route(self):
        """
        Test case for watch_namespaced_route

        watch changes to an object of kind Route
        """
        pass

    def test_watch_namespaced_route_list(self):
        """
        Test case for watch_namespaced_route_list

        watch individual changes to a list of Route
        """
        pass

    def test_watch_namespaced_template(self):
        """
        Test case for watch_namespaced_template

        watch changes to an object of kind Template
        """
        pass

    def test_watch_namespaced_template_list(self):
        """
        Test case for watch_namespaced_template_list

        watch individual changes to a list of Template
        """
        pass

    def test_watch_namespaced_user(self):
        """
        Test case for watch_namespaced_user

        watch changes to an object of kind User
        """
        pass

    def test_watch_namespaced_user_list(self):
        """
        Test case for watch_namespaced_user_list

        watch individual changes to a list of User
        """
        pass

    def test_watch_policy_binding_list(self):
        """
        Test case for watch_policy_binding_list

        watch individual changes to a list of PolicyBinding
        """
        pass

    def test_watch_policy_list(self):
        """
        Test case for watch_policy_list

        watch individual changes to a list of Policy
        """
        pass

    def test_watch_route_list(self):
        """
        Test case for watch_route_list

        watch individual changes to a list of Route
        """
        pass

    def test_watch_template_list(self):
        """
        Test case for watch_template_list

        watch individual changes to a list of Template
        """
        pass


if __name__ == '__main__':
    unittest.main()
