# coding: utf-8

"""
    

    

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import lib_openshift
from lib_openshift.rest import ApiException
from lib_openshift.apis.oapi_v1 import OapiV1


class TestOapiV1(unittest.TestCase):
    """ OapiV1 unit test stubs """

    def setUp(self):
        self.api = lib_openshift.apis.oapi_v1.OapiV1()

    def tearDown(self):
        pass

    def test_create_build(self):
        """
        Test case for create_build

        create a Build
        """
        pass

    def test_create_buildconfig(self):
        """
        Test case for create_buildconfig

        create a BuildConfig
        """
        pass

    def test_create_clusternetwork(self):
        """
        Test case for create_clusternetwork

        create a ClusterNetwork
        """
        pass

    def test_create_clusterpolicie(self):
        """
        Test case for create_clusterpolicie

        create a ClusterPolicy
        """
        pass

    def test_create_clusterpolicybinding(self):
        """
        Test case for create_clusterpolicybinding

        create a ClusterPolicyBinding
        """
        pass

    def test_create_clusterrole(self):
        """
        Test case for create_clusterrole

        create a ClusterRole
        """
        pass

    def test_create_clusterrolebinding(self):
        """
        Test case for create_clusterrolebinding

        create a ClusterRoleBinding
        """
        pass

    def test_create_deploymentconfig(self):
        """
        Test case for create_deploymentconfig

        create a DeploymentConfig
        """
        pass

    def test_create_deploymentconfigrollback(self):
        """
        Test case for create_deploymentconfigrollback

        create a DeploymentConfigRollback
        """
        pass

    def test_create_group(self):
        """
        Test case for create_group

        create a Group
        """
        pass

    def test_create_hostsubnet(self):
        """
        Test case for create_hostsubnet

        create a HostSubnet
        """
        pass

    def test_create_identitie(self):
        """
        Test case for create_identitie

        create a Identity
        """
        pass

    def test_create_image(self):
        """
        Test case for create_image

        create a Image
        """
        pass

    def test_create_imagestream(self):
        """
        Test case for create_imagestream

        create a ImageStream
        """
        pass

    def test_create_imagestreamimport(self):
        """
        Test case for create_imagestreamimport

        create a ImageStreamImport
        """
        pass

    def test_create_imagestreammapping(self):
        """
        Test case for create_imagestreammapping

        create a ImageStreamMapping
        """
        pass

    def test_create_localresourceaccessreview(self):
        """
        Test case for create_localresourceaccessreview

        create a LocalResourceAccessReview
        """
        pass

    def test_create_localsubjectaccessreview(self):
        """
        Test case for create_localsubjectaccessreview

        create a LocalSubjectAccessReview
        """
        pass

    def test_create_namespaced_build(self):
        """
        Test case for create_namespaced_build

        create a Build
        """
        pass

    def test_create_namespaced_build_clone(self):
        """
        Test case for create_namespaced_build_clone

        create clone of a BuildRequest
        """
        pass

    def test_create_namespaced_buildconfig(self):
        """
        Test case for create_namespaced_buildconfig

        create a BuildConfig
        """
        pass

    def test_create_namespaced_buildconfig_instantiate(self):
        """
        Test case for create_namespaced_buildconfig_instantiate

        create instantiate of a BuildRequest
        """
        pass

    def test_create_namespaced_buildconfig_instantiatebinary(self):
        """
        Test case for create_namespaced_buildconfig_instantiatebinary

        connect POST requests to instantiatebinary of BinaryBuildRequestOptions
        """
        pass

    def test_create_namespaced_buildconfig_webhook(self):
        """
        Test case for create_namespaced_buildconfig_webhook

        connect POST requests to webhooks of Status
        """
        pass

    def test_create_namespaced_buildconfig_webhookspath(self):
        """
        Test case for create_namespaced_buildconfig_webhookspath

        connect POST requests to webhooks of Status
        """
        pass

    def test_create_namespaced_deploymentconfig(self):
        """
        Test case for create_namespaced_deploymentconfig

        create a DeploymentConfig
        """
        pass

    def test_create_namespaced_deploymentconfigrollback(self):
        """
        Test case for create_namespaced_deploymentconfigrollback

        create a DeploymentConfigRollback
        """
        pass

    def test_create_namespaced_imagestream(self):
        """
        Test case for create_namespaced_imagestream

        create a ImageStream
        """
        pass

    def test_create_namespaced_imagestreamimport(self):
        """
        Test case for create_namespaced_imagestreamimport

        create a ImageStreamImport
        """
        pass

    def test_create_namespaced_imagestreammapping(self):
        """
        Test case for create_namespaced_imagestreammapping

        create a ImageStreamMapping
        """
        pass

    def test_create_namespaced_localresourceaccessreview(self):
        """
        Test case for create_namespaced_localresourceaccessreview

        create a LocalResourceAccessReview
        """
        pass

    def test_create_namespaced_localsubjectaccessreview(self):
        """
        Test case for create_namespaced_localsubjectaccessreview

        create a LocalSubjectAccessReview
        """
        pass

    def test_create_namespaced_policie(self):
        """
        Test case for create_namespaced_policie

        create a Policy
        """
        pass

    def test_create_namespaced_policybinding(self):
        """
        Test case for create_namespaced_policybinding

        create a PolicyBinding
        """
        pass

    def test_create_namespaced_processedtemplate(self):
        """
        Test case for create_namespaced_processedtemplate

        create a Template
        """
        pass

    def test_create_namespaced_resourceaccessreview(self):
        """
        Test case for create_namespaced_resourceaccessreview

        create a ResourceAccessReview
        """
        pass

    def test_create_namespaced_role(self):
        """
        Test case for create_namespaced_role

        create a Role
        """
        pass

    def test_create_namespaced_rolebinding(self):
        """
        Test case for create_namespaced_rolebinding

        create a RoleBinding
        """
        pass

    def test_create_namespaced_route(self):
        """
        Test case for create_namespaced_route

        create a Route
        """
        pass

    def test_create_namespaced_subjectaccessreview(self):
        """
        Test case for create_namespaced_subjectaccessreview

        create a SubjectAccessReview
        """
        pass

    def test_create_namespaced_template(self):
        """
        Test case for create_namespaced_template

        create a Template
        """
        pass

    def test_create_netnamespace(self):
        """
        Test case for create_netnamespace

        create a NetNamespace
        """
        pass

    def test_create_oauthaccesstoken(self):
        """
        Test case for create_oauthaccesstoken

        create a OAuthAccessToken
        """
        pass

    def test_create_oauthauthorizetoken(self):
        """
        Test case for create_oauthauthorizetoken

        create a OAuthAuthorizeToken
        """
        pass

    def test_create_oauthclient(self):
        """
        Test case for create_oauthclient

        create a OAuthClient
        """
        pass

    def test_create_oauthclientauthorization(self):
        """
        Test case for create_oauthclientauthorization

        create a OAuthClientAuthorization
        """
        pass

    def test_create_policie(self):
        """
        Test case for create_policie

        create a Policy
        """
        pass

    def test_create_policybinding(self):
        """
        Test case for create_policybinding

        create a PolicyBinding
        """
        pass

    def test_create_processedtemplate(self):
        """
        Test case for create_processedtemplate

        create a Template
        """
        pass

    def test_create_project(self):
        """
        Test case for create_project

        create a Project
        """
        pass

    def test_create_projectrequest(self):
        """
        Test case for create_projectrequest

        create a ProjectRequest
        """
        pass

    def test_create_resourceaccessreview(self):
        """
        Test case for create_resourceaccessreview

        create a ResourceAccessReview
        """
        pass

    def test_create_role(self):
        """
        Test case for create_role

        create a Role
        """
        pass

    def test_create_rolebinding(self):
        """
        Test case for create_rolebinding

        create a RoleBinding
        """
        pass

    def test_create_route(self):
        """
        Test case for create_route

        create a Route
        """
        pass

    def test_create_subjectaccessreview(self):
        """
        Test case for create_subjectaccessreview

        create a SubjectAccessReview
        """
        pass

    def test_create_template(self):
        """
        Test case for create_template

        create a Template
        """
        pass

    def test_create_user(self):
        """
        Test case for create_user

        create a User
        """
        pass

    def test_create_useridentitymapping(self):
        """
        Test case for create_useridentitymapping

        create a UserIdentityMapping
        """
        pass

    def test_delete_clusternetwork(self):
        """
        Test case for delete_clusternetwork

        delete a ClusterNetwork
        """
        pass

    def test_delete_clusternetworks(self):
        """
        Test case for delete_clusternetworks

        delete collection of ClusterNetwork
        """
        pass

    def test_delete_clusterpolicie(self):
        """
        Test case for delete_clusterpolicie

        delete a ClusterPolicy
        """
        pass

    def test_delete_clusterpolicies(self):
        """
        Test case for delete_clusterpolicies

        delete collection of ClusterPolicy
        """
        pass

    def test_delete_clusterpolicybinding(self):
        """
        Test case for delete_clusterpolicybinding

        delete a ClusterPolicyBinding
        """
        pass

    def test_delete_clusterpolicybindings(self):
        """
        Test case for delete_clusterpolicybindings

        delete collection of ClusterPolicyBinding
        """
        pass

    def test_delete_clusterrole(self):
        """
        Test case for delete_clusterrole

        delete a ClusterRole
        """
        pass

    def test_delete_clusterrolebinding(self):
        """
        Test case for delete_clusterrolebinding

        delete a ClusterRoleBinding
        """
        pass

    def test_delete_group(self):
        """
        Test case for delete_group

        delete a Group
        """
        pass

    def test_delete_groups(self):
        """
        Test case for delete_groups

        delete collection of Group
        """
        pass

    def test_delete_hostsubnet(self):
        """
        Test case for delete_hostsubnet

        delete a HostSubnet
        """
        pass

    def test_delete_hostsubnets(self):
        """
        Test case for delete_hostsubnets

        delete collection of HostSubnet
        """
        pass

    def test_delete_identitie(self):
        """
        Test case for delete_identitie

        delete a Identity
        """
        pass

    def test_delete_identities(self):
        """
        Test case for delete_identities

        delete collection of Identity
        """
        pass

    def test_delete_image(self):
        """
        Test case for delete_image

        delete a Image
        """
        pass

    def test_delete_images(self):
        """
        Test case for delete_images

        delete collection of Image
        """
        pass

    def test_delete_namespaced_build(self):
        """
        Test case for delete_namespaced_build

        delete a Build
        """
        pass

    def test_delete_namespaced_buildconfig(self):
        """
        Test case for delete_namespaced_buildconfig

        delete a BuildConfig
        """
        pass

    def test_delete_namespaced_buildconfigs(self):
        """
        Test case for delete_namespaced_buildconfigs

        delete collection of BuildConfig
        """
        pass

    def test_delete_namespaced_builds(self):
        """
        Test case for delete_namespaced_builds

        delete collection of Build
        """
        pass

    def test_delete_namespaced_deploymentconfig(self):
        """
        Test case for delete_namespaced_deploymentconfig

        delete a DeploymentConfig
        """
        pass

    def test_delete_namespaced_deploymentconfigs(self):
        """
        Test case for delete_namespaced_deploymentconfigs

        delete collection of DeploymentConfig
        """
        pass

    def test_delete_namespaced_imagestream(self):
        """
        Test case for delete_namespaced_imagestream

        delete a ImageStream
        """
        pass

    def test_delete_namespaced_imagestreams(self):
        """
        Test case for delete_namespaced_imagestreams

        delete collection of ImageStream
        """
        pass

    def test_delete_namespaced_imagestreamtag(self):
        """
        Test case for delete_namespaced_imagestreamtag

        delete a ImageStreamTag
        """
        pass

    def test_delete_namespaced_policie(self):
        """
        Test case for delete_namespaced_policie

        delete a Policy
        """
        pass

    def test_delete_namespaced_policies(self):
        """
        Test case for delete_namespaced_policies

        delete collection of Policy
        """
        pass

    def test_delete_namespaced_policybinding(self):
        """
        Test case for delete_namespaced_policybinding

        delete a PolicyBinding
        """
        pass

    def test_delete_namespaced_policybindings(self):
        """
        Test case for delete_namespaced_policybindings

        delete collection of PolicyBinding
        """
        pass

    def test_delete_namespaced_role(self):
        """
        Test case for delete_namespaced_role

        delete a Role
        """
        pass

    def test_delete_namespaced_rolebinding(self):
        """
        Test case for delete_namespaced_rolebinding

        delete a RoleBinding
        """
        pass

    def test_delete_namespaced_route(self):
        """
        Test case for delete_namespaced_route

        delete a Route
        """
        pass

    def test_delete_namespaced_routes(self):
        """
        Test case for delete_namespaced_routes

        delete collection of Route
        """
        pass

    def test_delete_namespaced_template(self):
        """
        Test case for delete_namespaced_template

        delete a Template
        """
        pass

    def test_delete_namespaced_templates(self):
        """
        Test case for delete_namespaced_templates

        delete collection of Template
        """
        pass

    def test_delete_netnamespace(self):
        """
        Test case for delete_netnamespace

        delete a NetNamespace
        """
        pass

    def test_delete_netnamespaces(self):
        """
        Test case for delete_netnamespaces

        delete collection of NetNamespace
        """
        pass

    def test_delete_oauthaccesstoken(self):
        """
        Test case for delete_oauthaccesstoken

        delete a OAuthAccessToken
        """
        pass

    def test_delete_oauthauthorizetoken(self):
        """
        Test case for delete_oauthauthorizetoken

        delete a OAuthAuthorizeToken
        """
        pass

    def test_delete_oauthclient(self):
        """
        Test case for delete_oauthclient

        delete a OAuthClient
        """
        pass

    def test_delete_oauthclientauthorization(self):
        """
        Test case for delete_oauthclientauthorization

        delete a OAuthClientAuthorization
        """
        pass

    def test_delete_oauthclientauthorizations(self):
        """
        Test case for delete_oauthclientauthorizations

        delete collection of OAuthClientAuthorization
        """
        pass

    def test_delete_oauthclients(self):
        """
        Test case for delete_oauthclients

        delete collection of OAuthClient
        """
        pass

    def test_delete_project(self):
        """
        Test case for delete_project

        delete a Project
        """
        pass

    def test_delete_user(self):
        """
        Test case for delete_user

        delete a User
        """
        pass

    def test_delete_useridentitymapping(self):
        """
        Test case for delete_useridentitymapping

        delete a UserIdentityMapping
        """
        pass

    def test_delete_users(self):
        """
        Test case for delete_users

        delete collection of User
        """
        pass

    def test_get_clusternetwork(self):
        """
        Test case for get_clusternetwork

        read the specified ClusterNetwork
        """
        pass

    def test_get_clusterpolicie(self):
        """
        Test case for get_clusterpolicie

        read the specified ClusterPolicy
        """
        pass

    def test_get_clusterpolicybinding(self):
        """
        Test case for get_clusterpolicybinding

        read the specified ClusterPolicyBinding
        """
        pass

    def test_get_clusterrole(self):
        """
        Test case for get_clusterrole

        read the specified ClusterRole
        """
        pass

    def test_get_clusterrolebinding(self):
        """
        Test case for get_clusterrolebinding

        read the specified ClusterRoleBinding
        """
        pass

    def test_get_group(self):
        """
        Test case for get_group

        read the specified Group
        """
        pass

    def test_get_hostsubnet(self):
        """
        Test case for get_hostsubnet

        read the specified HostSubnet
        """
        pass

    def test_get_identitie(self):
        """
        Test case for get_identitie

        read the specified Identity
        """
        pass

    def test_get_image(self):
        """
        Test case for get_image

        read the specified Image
        """
        pass

    def test_get_namespaced_build(self):
        """
        Test case for get_namespaced_build

        read the specified Build
        """
        pass

    def test_get_namespaced_build_log(self):
        """
        Test case for get_namespaced_build_log

        read log of the specified BuildLog
        """
        pass

    def test_get_namespaced_buildconfig(self):
        """
        Test case for get_namespaced_buildconfig

        read the specified BuildConfig
        """
        pass

    def test_get_namespaced_deploymentconfig(self):
        """
        Test case for get_namespaced_deploymentconfig

        read the specified DeploymentConfig
        """
        pass

    def test_get_namespaced_deploymentconfig_log(self):
        """
        Test case for get_namespaced_deploymentconfig_log

        read log of the specified DeploymentLog
        """
        pass

    def test_get_namespaced_deploymentconfig_scale(self):
        """
        Test case for get_namespaced_deploymentconfig_scale

        read scale of the specified Scale
        """
        pass

    def test_get_namespaced_generatedeploymentconfig(self):
        """
        Test case for get_namespaced_generatedeploymentconfig

        read the specified DeploymentConfig
        """
        pass

    def test_get_namespaced_imagestream(self):
        """
        Test case for get_namespaced_imagestream

        read the specified ImageStream
        """
        pass

    def test_get_namespaced_imagestream_secrets(self):
        """
        Test case for get_namespaced_imagestream_secrets

        read secrets of the specified SecretList
        """
        pass

    def test_get_namespaced_imagestreamimage(self):
        """
        Test case for get_namespaced_imagestreamimage

        read the specified ImageStreamImage
        """
        pass

    def test_get_namespaced_imagestreamtag(self):
        """
        Test case for get_namespaced_imagestreamtag

        read the specified ImageStreamTag
        """
        pass

    def test_get_namespaced_policie(self):
        """
        Test case for get_namespaced_policie

        read the specified Policy
        """
        pass

    def test_get_namespaced_policybinding(self):
        """
        Test case for get_namespaced_policybinding

        read the specified PolicyBinding
        """
        pass

    def test_get_namespaced_role(self):
        """
        Test case for get_namespaced_role

        read the specified Role
        """
        pass

    def test_get_namespaced_rolebinding(self):
        """
        Test case for get_namespaced_rolebinding

        read the specified RoleBinding
        """
        pass

    def test_get_namespaced_route(self):
        """
        Test case for get_namespaced_route

        read the specified Route
        """
        pass

    def test_get_namespaced_template(self):
        """
        Test case for get_namespaced_template

        read the specified Template
        """
        pass

    def test_get_netnamespace(self):
        """
        Test case for get_netnamespace

        read the specified NetNamespace
        """
        pass

    def test_get_oauthaccesstoken(self):
        """
        Test case for get_oauthaccesstoken

        read the specified OAuthAccessToken
        """
        pass

    def test_get_oauthauthorizetoken(self):
        """
        Test case for get_oauthauthorizetoken

        read the specified OAuthAuthorizeToken
        """
        pass

    def test_get_oauthclient(self):
        """
        Test case for get_oauthclient

        read the specified OAuthClient
        """
        pass

    def test_get_oauthclientauthorization(self):
        """
        Test case for get_oauthclientauthorization

        read the specified OAuthClientAuthorization
        """
        pass

    def test_get_project(self):
        """
        Test case for get_project

        read the specified Project
        """
        pass

    def test_get_user(self):
        """
        Test case for get_user

        read the specified User
        """
        pass

    def test_get_useridentitymapping(self):
        """
        Test case for get_useridentitymapping

        read the specified UserIdentityMapping
        """
        pass

    def test_list(self):
        """
        Test case for list

        get available resources
        """
        pass

    def test_list_buildconfigs(self):
        """
        Test case for list_buildconfigs

        list or watch objects of kind BuildConfig
        """
        pass

    def test_list_builds(self):
        """
        Test case for list_builds

        list or watch objects of kind Build
        """
        pass

    def test_list_clusternetworks(self):
        """
        Test case for list_clusternetworks

        list or watch objects of kind ClusterNetwork
        """
        pass

    def test_list_clusterpolicies(self):
        """
        Test case for list_clusterpolicies

        list or watch objects of kind ClusterPolicy
        """
        pass

    def test_list_clusterpolicybindings(self):
        """
        Test case for list_clusterpolicybindings

        list or watch objects of kind ClusterPolicyBinding
        """
        pass

    def test_list_clusterrolebindings(self):
        """
        Test case for list_clusterrolebindings

        list objects of kind ClusterRoleBinding
        """
        pass

    def test_list_clusterroles(self):
        """
        Test case for list_clusterroles

        list objects of kind ClusterRole
        """
        pass

    def test_list_deploymentconfigs(self):
        """
        Test case for list_deploymentconfigs

        list or watch objects of kind DeploymentConfig
        """
        pass

    def test_list_groups(self):
        """
        Test case for list_groups

        list or watch objects of kind Group
        """
        pass

    def test_list_hostsubnets(self):
        """
        Test case for list_hostsubnets

        list or watch objects of kind HostSubnet
        """
        pass

    def test_list_identities(self):
        """
        Test case for list_identities

        list or watch objects of kind Identity
        """
        pass

    def test_list_images(self):
        """
        Test case for list_images

        list or watch objects of kind Image
        """
        pass

    def test_list_imagestreams(self):
        """
        Test case for list_imagestreams

        list or watch objects of kind ImageStream
        """
        pass

    def test_list_imagestreamtags(self):
        """
        Test case for list_imagestreamtags

        list objects of kind ImageStreamTag
        """
        pass

    def test_list_namespaced_buildconfigs(self):
        """
        Test case for list_namespaced_buildconfigs

        list or watch objects of kind BuildConfig
        """
        pass

    def test_list_namespaced_builds(self):
        """
        Test case for list_namespaced_builds

        list or watch objects of kind Build
        """
        pass

    def test_list_namespaced_deploymentconfigs(self):
        """
        Test case for list_namespaced_deploymentconfigs

        list or watch objects of kind DeploymentConfig
        """
        pass

    def test_list_namespaced_imagestreams(self):
        """
        Test case for list_namespaced_imagestreams

        list or watch objects of kind ImageStream
        """
        pass

    def test_list_namespaced_imagestreamtags(self):
        """
        Test case for list_namespaced_imagestreamtags

        list objects of kind ImageStreamTag
        """
        pass

    def test_list_namespaced_policies(self):
        """
        Test case for list_namespaced_policies

        list or watch objects of kind Policy
        """
        pass

    def test_list_namespaced_policybindings(self):
        """
        Test case for list_namespaced_policybindings

        list or watch objects of kind PolicyBinding
        """
        pass

    def test_list_namespaced_rolebindings(self):
        """
        Test case for list_namespaced_rolebindings

        list objects of kind RoleBinding
        """
        pass

    def test_list_namespaced_roles(self):
        """
        Test case for list_namespaced_roles

        list objects of kind Role
        """
        pass

    def test_list_namespaced_routes(self):
        """
        Test case for list_namespaced_routes

        list or watch objects of kind Route
        """
        pass

    def test_list_namespaced_templates(self):
        """
        Test case for list_namespaced_templates

        list or watch objects of kind Template
        """
        pass

    def test_list_netnamespaces(self):
        """
        Test case for list_netnamespaces

        list or watch objects of kind NetNamespace
        """
        pass

    def test_list_oauthaccesstokens(self):
        """
        Test case for list_oauthaccesstokens

        list objects of kind OAuthAccessToken
        """
        pass

    def test_list_oauthauthorizetokens(self):
        """
        Test case for list_oauthauthorizetokens

        list objects of kind OAuthAuthorizeToken
        """
        pass

    def test_list_oauthclientauthorizations(self):
        """
        Test case for list_oauthclientauthorizations

        list or watch objects of kind OAuthClientAuthorization
        """
        pass

    def test_list_oauthclients(self):
        """
        Test case for list_oauthclients

        list or watch objects of kind OAuthClient
        """
        pass

    def test_list_policies(self):
        """
        Test case for list_policies

        list or watch objects of kind Policy
        """
        pass

    def test_list_policybindings(self):
        """
        Test case for list_policybindings

        list or watch objects of kind PolicyBinding
        """
        pass

    def test_list_projectrequests(self):
        """
        Test case for list_projectrequests

        list objects of kind ProjectRequest
        """
        pass

    def test_list_projects(self):
        """
        Test case for list_projects

        list objects of kind Project
        """
        pass

    def test_list_rolebindings(self):
        """
        Test case for list_rolebindings

        list objects of kind RoleBinding
        """
        pass

    def test_list_roles(self):
        """
        Test case for list_roles

        list objects of kind Role
        """
        pass

    def test_list_routes(self):
        """
        Test case for list_routes

        list or watch objects of kind Route
        """
        pass

    def test_list_templates(self):
        """
        Test case for list_templates

        list or watch objects of kind Template
        """
        pass

    def test_list_users(self):
        """
        Test case for list_users

        list or watch objects of kind User
        """
        pass

    def test_patch_clusternetwork(self):
        """
        Test case for patch_clusternetwork

        partially update the specified ClusterNetwork
        """
        pass

    def test_patch_clusterpolicie(self):
        """
        Test case for patch_clusterpolicie

        partially update the specified ClusterPolicy
        """
        pass

    def test_patch_clusterpolicybinding(self):
        """
        Test case for patch_clusterpolicybinding

        partially update the specified ClusterPolicyBinding
        """
        pass

    def test_patch_clusterrole(self):
        """
        Test case for patch_clusterrole

        partially update the specified ClusterRole
        """
        pass

    def test_patch_clusterrolebinding(self):
        """
        Test case for patch_clusterrolebinding

        partially update the specified ClusterRoleBinding
        """
        pass

    def test_patch_group(self):
        """
        Test case for patch_group

        partially update the specified Group
        """
        pass

    def test_patch_hostsubnet(self):
        """
        Test case for patch_hostsubnet

        partially update the specified HostSubnet
        """
        pass

    def test_patch_identitie(self):
        """
        Test case for patch_identitie

        partially update the specified Identity
        """
        pass

    def test_patch_image(self):
        """
        Test case for patch_image

        partially update the specified Image
        """
        pass

    def test_patch_namespaced_build(self):
        """
        Test case for patch_namespaced_build

        partially update the specified Build
        """
        pass

    def test_patch_namespaced_buildconfig(self):
        """
        Test case for patch_namespaced_buildconfig

        partially update the specified BuildConfig
        """
        pass

    def test_patch_namespaced_deploymentconfig(self):
        """
        Test case for patch_namespaced_deploymentconfig

        partially update the specified DeploymentConfig
        """
        pass

    def test_patch_namespaced_deploymentconfig_scale(self):
        """
        Test case for patch_namespaced_deploymentconfig_scale

        partially update scale of the specified Scale
        """
        pass

    def test_patch_namespaced_imagestream(self):
        """
        Test case for patch_namespaced_imagestream

        partially update the specified ImageStream
        """
        pass

    def test_patch_namespaced_imagestreamtag(self):
        """
        Test case for patch_namespaced_imagestreamtag

        partially update the specified ImageStreamTag
        """
        pass

    def test_patch_namespaced_policie(self):
        """
        Test case for patch_namespaced_policie

        partially update the specified Policy
        """
        pass

    def test_patch_namespaced_policybinding(self):
        """
        Test case for patch_namespaced_policybinding

        partially update the specified PolicyBinding
        """
        pass

    def test_patch_namespaced_role(self):
        """
        Test case for patch_namespaced_role

        partially update the specified Role
        """
        pass

    def test_patch_namespaced_rolebinding(self):
        """
        Test case for patch_namespaced_rolebinding

        partially update the specified RoleBinding
        """
        pass

    def test_patch_namespaced_route(self):
        """
        Test case for patch_namespaced_route

        partially update the specified Route
        """
        pass

    def test_patch_namespaced_template(self):
        """
        Test case for patch_namespaced_template

        partially update the specified Template
        """
        pass

    def test_patch_netnamespace(self):
        """
        Test case for patch_netnamespace

        partially update the specified NetNamespace
        """
        pass

    def test_patch_oauthclient(self):
        """
        Test case for patch_oauthclient

        partially update the specified OAuthClient
        """
        pass

    def test_patch_oauthclientauthorization(self):
        """
        Test case for patch_oauthclientauthorization

        partially update the specified OAuthClientAuthorization
        """
        pass

    def test_patch_project(self):
        """
        Test case for patch_project

        partially update the specified Project
        """
        pass

    def test_patch_user(self):
        """
        Test case for patch_user

        partially update the specified User
        """
        pass

    def test_patch_useridentitymapping(self):
        """
        Test case for patch_useridentitymapping

        partially update the specified UserIdentityMapping
        """
        pass

    def test_replace_clusternetwork(self):
        """
        Test case for replace_clusternetwork

        replace the specified ClusterNetwork
        """
        pass

    def test_replace_clusterpolicie(self):
        """
        Test case for replace_clusterpolicie

        replace the specified ClusterPolicy
        """
        pass

    def test_replace_clusterpolicybinding(self):
        """
        Test case for replace_clusterpolicybinding

        replace the specified ClusterPolicyBinding
        """
        pass

    def test_replace_clusterrole(self):
        """
        Test case for replace_clusterrole

        replace the specified ClusterRole
        """
        pass

    def test_replace_clusterrolebinding(self):
        """
        Test case for replace_clusterrolebinding

        replace the specified ClusterRoleBinding
        """
        pass

    def test_replace_group(self):
        """
        Test case for replace_group

        replace the specified Group
        """
        pass

    def test_replace_hostsubnet(self):
        """
        Test case for replace_hostsubnet

        replace the specified HostSubnet
        """
        pass

    def test_replace_identitie(self):
        """
        Test case for replace_identitie

        replace the specified Identity
        """
        pass

    def test_replace_image(self):
        """
        Test case for replace_image

        replace the specified Image
        """
        pass

    def test_replace_namespaced_build(self):
        """
        Test case for replace_namespaced_build

        replace the specified Build
        """
        pass

    def test_replace_namespaced_build_details(self):
        """
        Test case for replace_namespaced_build_details

        replace details of the specified Build
        """
        pass

    def test_replace_namespaced_buildconfig(self):
        """
        Test case for replace_namespaced_buildconfig

        replace the specified BuildConfig
        """
        pass

    def test_replace_namespaced_deploymentconfig(self):
        """
        Test case for replace_namespaced_deploymentconfig

        replace the specified DeploymentConfig
        """
        pass

    def test_replace_namespaced_deploymentconfig_scale(self):
        """
        Test case for replace_namespaced_deploymentconfig_scale

        replace scale of the specified Scale
        """
        pass

    def test_replace_namespaced_imagestream(self):
        """
        Test case for replace_namespaced_imagestream

        replace the specified ImageStream
        """
        pass

    def test_replace_namespaced_imagestream_status(self):
        """
        Test case for replace_namespaced_imagestream_status

        replace status of the specified ImageStream
        """
        pass

    def test_replace_namespaced_imagestreamtag(self):
        """
        Test case for replace_namespaced_imagestreamtag

        replace the specified ImageStreamTag
        """
        pass

    def test_replace_namespaced_policie(self):
        """
        Test case for replace_namespaced_policie

        replace the specified Policy
        """
        pass

    def test_replace_namespaced_policybinding(self):
        """
        Test case for replace_namespaced_policybinding

        replace the specified PolicyBinding
        """
        pass

    def test_replace_namespaced_role(self):
        """
        Test case for replace_namespaced_role

        replace the specified Role
        """
        pass

    def test_replace_namespaced_rolebinding(self):
        """
        Test case for replace_namespaced_rolebinding

        replace the specified RoleBinding
        """
        pass

    def test_replace_namespaced_route(self):
        """
        Test case for replace_namespaced_route

        replace the specified Route
        """
        pass

    def test_replace_namespaced_route_status(self):
        """
        Test case for replace_namespaced_route_status

        replace status of the specified Route
        """
        pass

    def test_replace_namespaced_template(self):
        """
        Test case for replace_namespaced_template

        replace the specified Template
        """
        pass

    def test_replace_netnamespace(self):
        """
        Test case for replace_netnamespace

        replace the specified NetNamespace
        """
        pass

    def test_replace_oauthclient(self):
        """
        Test case for replace_oauthclient

        replace the specified OAuthClient
        """
        pass

    def test_replace_oauthclientauthorization(self):
        """
        Test case for replace_oauthclientauthorization

        replace the specified OAuthClientAuthorization
        """
        pass

    def test_replace_project(self):
        """
        Test case for replace_project

        replace the specified Project
        """
        pass

    def test_replace_user(self):
        """
        Test case for replace_user

        replace the specified User
        """
        pass

    def test_replace_useridentitymapping(self):
        """
        Test case for replace_useridentitymapping

        replace the specified UserIdentityMapping
        """
        pass

    def test_watch_namespaced_watch_build(self):
        """
        Test case for watch_namespaced_watch_build

        watch changes to an object of kind Build
        """
        pass

    def test_watch_namespaced_watch_buildconfig(self):
        """
        Test case for watch_namespaced_watch_buildconfig

        watch changes to an object of kind BuildConfig
        """
        pass

    def test_watch_namespaced_watch_buildconfigs(self):
        """
        Test case for watch_namespaced_watch_buildconfigs

        watch individual changes to a list of BuildConfig
        """
        pass

    def test_watch_namespaced_watch_builds(self):
        """
        Test case for watch_namespaced_watch_builds

        watch individual changes to a list of Build
        """
        pass

    def test_watch_namespaced_watch_deploymentconfig(self):
        """
        Test case for watch_namespaced_watch_deploymentconfig

        watch changes to an object of kind DeploymentConfig
        """
        pass

    def test_watch_namespaced_watch_deploymentconfigs(self):
        """
        Test case for watch_namespaced_watch_deploymentconfigs

        watch individual changes to a list of DeploymentConfig
        """
        pass

    def test_watch_namespaced_watch_imagestream(self):
        """
        Test case for watch_namespaced_watch_imagestream

        watch changes to an object of kind ImageStream
        """
        pass

    def test_watch_namespaced_watch_imagestreams(self):
        """
        Test case for watch_namespaced_watch_imagestreams

        watch individual changes to a list of ImageStream
        """
        pass

    def test_watch_namespaced_watch_policie(self):
        """
        Test case for watch_namespaced_watch_policie

        watch changes to an object of kind Policy
        """
        pass

    def test_watch_namespaced_watch_policies(self):
        """
        Test case for watch_namespaced_watch_policies

        watch individual changes to a list of Policy
        """
        pass

    def test_watch_namespaced_watch_policybinding(self):
        """
        Test case for watch_namespaced_watch_policybinding

        watch changes to an object of kind PolicyBinding
        """
        pass

    def test_watch_namespaced_watch_policybindings(self):
        """
        Test case for watch_namespaced_watch_policybindings

        watch individual changes to a list of PolicyBinding
        """
        pass

    def test_watch_namespaced_watch_route(self):
        """
        Test case for watch_namespaced_watch_route

        watch changes to an object of kind Route
        """
        pass

    def test_watch_namespaced_watch_routes(self):
        """
        Test case for watch_namespaced_watch_routes

        watch individual changes to a list of Route
        """
        pass

    def test_watch_namespaced_watch_template(self):
        """
        Test case for watch_namespaced_watch_template

        watch changes to an object of kind Template
        """
        pass

    def test_watch_namespaced_watch_templates(self):
        """
        Test case for watch_namespaced_watch_templates

        watch individual changes to a list of Template
        """
        pass

    def test_watch_watch_buildconfigs(self):
        """
        Test case for watch_watch_buildconfigs

        watch individual changes to a list of BuildConfig
        """
        pass

    def test_watch_watch_builds(self):
        """
        Test case for watch_watch_builds

        watch individual changes to a list of Build
        """
        pass

    def test_watch_watch_clusternetwork(self):
        """
        Test case for watch_watch_clusternetwork

        watch changes to an object of kind ClusterNetwork
        """
        pass

    def test_watch_watch_clusternetworks(self):
        """
        Test case for watch_watch_clusternetworks

        watch individual changes to a list of ClusterNetwork
        """
        pass

    def test_watch_watch_clusterpolicie(self):
        """
        Test case for watch_watch_clusterpolicie

        watch changes to an object of kind ClusterPolicy
        """
        pass

    def test_watch_watch_clusterpolicies(self):
        """
        Test case for watch_watch_clusterpolicies

        watch individual changes to a list of ClusterPolicy
        """
        pass

    def test_watch_watch_clusterpolicybinding(self):
        """
        Test case for watch_watch_clusterpolicybinding

        watch changes to an object of kind ClusterPolicyBinding
        """
        pass

    def test_watch_watch_clusterpolicybindings(self):
        """
        Test case for watch_watch_clusterpolicybindings

        watch individual changes to a list of ClusterPolicyBinding
        """
        pass

    def test_watch_watch_deploymentconfigs(self):
        """
        Test case for watch_watch_deploymentconfigs

        watch individual changes to a list of DeploymentConfig
        """
        pass

    def test_watch_watch_group(self):
        """
        Test case for watch_watch_group

        watch changes to an object of kind Group
        """
        pass

    def test_watch_watch_groups(self):
        """
        Test case for watch_watch_groups

        watch individual changes to a list of Group
        """
        pass

    def test_watch_watch_hostsubnet(self):
        """
        Test case for watch_watch_hostsubnet

        watch changes to an object of kind HostSubnet
        """
        pass

    def test_watch_watch_hostsubnets(self):
        """
        Test case for watch_watch_hostsubnets

        watch individual changes to a list of HostSubnet
        """
        pass

    def test_watch_watch_identitie(self):
        """
        Test case for watch_watch_identitie

        watch changes to an object of kind Identity
        """
        pass

    def test_watch_watch_identities(self):
        """
        Test case for watch_watch_identities

        watch individual changes to a list of Identity
        """
        pass

    def test_watch_watch_image(self):
        """
        Test case for watch_watch_image

        watch changes to an object of kind Image
        """
        pass

    def test_watch_watch_images(self):
        """
        Test case for watch_watch_images

        watch individual changes to a list of Image
        """
        pass

    def test_watch_watch_imagestreams(self):
        """
        Test case for watch_watch_imagestreams

        watch individual changes to a list of ImageStream
        """
        pass

    def test_watch_watch_netnamespace(self):
        """
        Test case for watch_watch_netnamespace

        watch changes to an object of kind NetNamespace
        """
        pass

    def test_watch_watch_netnamespaces(self):
        """
        Test case for watch_watch_netnamespaces

        watch individual changes to a list of NetNamespace
        """
        pass

    def test_watch_watch_oauthclient(self):
        """
        Test case for watch_watch_oauthclient

        watch changes to an object of kind OAuthClient
        """
        pass

    def test_watch_watch_oauthclientauthorization(self):
        """
        Test case for watch_watch_oauthclientauthorization

        watch changes to an object of kind OAuthClientAuthorization
        """
        pass

    def test_watch_watch_oauthclientauthorizations(self):
        """
        Test case for watch_watch_oauthclientauthorizations

        watch individual changes to a list of OAuthClientAuthorization
        """
        pass

    def test_watch_watch_oauthclients(self):
        """
        Test case for watch_watch_oauthclients

        watch individual changes to a list of OAuthClient
        """
        pass

    def test_watch_watch_policies(self):
        """
        Test case for watch_watch_policies

        watch individual changes to a list of Policy
        """
        pass

    def test_watch_watch_policybindings(self):
        """
        Test case for watch_watch_policybindings

        watch individual changes to a list of PolicyBinding
        """
        pass

    def test_watch_watch_routes(self):
        """
        Test case for watch_watch_routes

        watch individual changes to a list of Route
        """
        pass

    def test_watch_watch_templates(self):
        """
        Test case for watch_watch_templates

        watch individual changes to a list of Template
        """
        pass

    def test_watch_watch_user(self):
        """
        Test case for watch_watch_user

        watch changes to an object of kind User
        """
        pass

    def test_watch_watch_users(self):
        """
        Test case for watch_watch_users

        watch individual changes to a list of User
        """
        pass


if __name__ == '__main__':
    unittest.main()
